name: Deploy PHP App to cPanel Shared Hosting

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install FTP client
      run: sudo apt-get update && sudo apt-get install -y lftp

    - name: Deploy PHP app to cPanel Shared Hosting
      run: |
        lftp -c "open -u ${{ secrets.CPANEL_USERNAME }},$${{ secrets.CPANEL_PASSWORD }} -e 'mirror -R ./ /public_html; bye;' ${{ secrets.CPANEL_HOST }}"
